In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import datetime as dt

In [2]:
cust=pd.read_csv("D:\Analytic_X_lab\Python\Assigment\Python Foundation Case Study 1 - Retail Case Study\Case Study 1 - Retail Case Study\Customer.csv")

In [3]:
cust.head(2)

   customer_Id         DOB Gender  city_code
0       268408  02-01-1970      M        4.0
1       269696  07-01-1970      F        8.0

In [4]:
prod=pd.read_csv("D:\Analytic_X_lab\Python\Assigment\Python Foundation Case Study 1 - Retail Case Study\Case Study 1 - Retail Case Study\prod_cat_info.csv")

In [5]:
prod.head(2)

   prod_cat_code  prod_cat  prod_sub_cat_code prod_subcat
0              1  Clothing                  4        Mens
1              1  Clothing                  1       Women

In [6]:
trans=pd.read_csv("D:\Analytic_X_lab\Python\Assigment\Python Foundation Case Study 1 - Retail Case Study\Case Study 1 - Retail Case Study\Transactions.csv")

In [7]:
trans.head(2)

,transaction_id,cust_id,tran_date,prod_subcat_code,prod_cat_code,Qty,Rate,Tax,total_amt,Store_type
0,80712190438,270351,28-02-2014,1,1,-5,-772,405.300,-4265.300,e-Shop
1,29258453508,270384,27-02-2014,5,3,-5,-1497,785.925,-8270.925,e-Shop

### 1. Merge the datasets Customers, Product Hierarchy and Transactions as Customer_Final. Ensure to keep all customers who have done transactions with us and select the join type accordingly.

In [8]:
cust_tran=pd.merge(left=cust,right=trans,left_on='customer_Id',right_on='cust_id',how='left',suffixes=('_cust','_trans'))

In [9]:
cust_tran.head(2)

,customer_Id,DOB,Gender,city_code,transaction_id,cust_id,tran_date,prod_subcat_code,prod_cat_code,Qty,Rate,Tax,total_amt,Store_type
0,268408,02-01-1970,M,4.0,8.724384e+10,268408.0,13-01-2014,7.0,5.0,5.0,187.0,98.175,1033.175,TeleShop
1,268408,02-01-1970,M,4.0,1.619787e+10,268408.0,16-12-2013,1.0,4.0,-5.0,-210.0,110.250,-1160.250,Flagship store

In [10]:
cust_tran.drop('cust_id',axis=1,inplace=True)

In [11]:
cust_tran_prod=pd.merge(
    left=cust_tran,right=prod,left_on=['prod_subcat_code','prod_cat_code'],right_on=['prod_sub_cat_code','prod_cat_code'],how='left',
    suffixes=('_tran','_prod')



)

In [12]:
cust_tran_prod.head(2)

,customer_Id,DOB,Gender,city_code,transaction_id,tran_date,prod_subcat_code,prod_cat_code,Qty,Rate,Tax,total_amt,Store_type,prod_cat,prod_sub_cat_code,prod_subcat
0,268408,02-01-1970,M,4.0,8.724384e+10,13-01-2014,7.0,5.0,5.0,187.0,98.175,1033.175,TeleShop,Books,7.0,Fiction
1,268408,02-01-1970,M,4.0,1.619787e+10,16-12-2013,1.0,4.0,-5.0,-210.0,110.250,-1160.250,Flagship store,Bags,1.0,Mens

### 2. Prepare a summary report for the merged data set.-
--------------------------------------------------------
### a. Get the column names and their corresponding data types

In [13]:
cust_tran_prod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23194 entries, 0 to 23193
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_Id        23194 non-null  int64
 1   DOB                23194 non-null  object
 2   Gender             23185 non-null  object
 3   city_code          23186 non-null  float64
 4   transaction_id     23053 non-null  float64
 5   tran_date          23053 non-null  object
 6   prod_subcat_code   23053 non-null  float64
 7   prod_cat_code      23053 non-null  float64
 8   Qty                23053 non-null  float64
 9   Rate               23053 non-null  float64
 10  Tax                23053 non-null  float64
 11  total_amt          23053 non-null  float64
 12  Store_type         23053 non-null  object
 13  prod_cat           23053 non-null  object
 14  prod_sub_cat_code  23053 non-null  float64
 15  prod_subcat        23053 non-null  object
dtypes: float64(9), int64(1), object(6)
memory usage: 2.8+ MB

### b. Top/Bottom 10 observation

In [14]:
cust_tran_prod.head(10)

,customer_Id,DOB,Gender,city_code,transaction_id,tran_date,prod_subcat_code,prod_cat_code,Qty,Rate,Tax,total_amt,Store_type,prod_cat,prod_sub_cat_code,prod_subcat
0,268408,02-01-1970,M,4.0,8.724384e+10,13-01-2014,7.0,5.0,5.0,187.0,98.175,1033.175,TeleShop,Books,7.0,Fiction
1,268408,02-01-1970,M,4.0,1.619787e+10,16-12-2013,1.0,4.0,-5.0,-210.0,110.250,-1160.250,Flagship store,Bags,1.0,Mens
2,268408,02-01-1970,M,4.0,1.619787e+10,12/12/2013,1.0,4.0,5.0,210.0,110.250,1160.250,Flagship store,Bags,1.0,Mens
3,268408,02-01-1970,M,4.0,2.881014e+10,2/9/2013,10.0,6.0,2.0,813.0,170.730,1796.730,TeleShop,Home and kitchen,10.0,Kitchen
4,268408,02-01-1970,M,4.0,6.463344e+10,6/5/2013,4.0,2.0,3.0,312.0,98.280,1034.280,Flagship store,Footwear,4.0,Kids
5,268408,02-01-1970,M,4.0,5.690286e+10,30-01-2013,9.0,3.0,5.0,868.0,455.700,4795.700,e-Shop,Electronics,9.0,Cameras
6,268408,02-01-1970,M,4.0,5.684453e+10,14-10-2012,1.0,2.0,5.0,1175.0,616.875,6491.875,MBR,Footwear,1.0,Mens
7,268408,02-01-1970,M,4.0,1.951606e+10,7/9/2012,10.0,3.0,4.0,650.0,273.000,2873.000,e-Shop,Electronics,10.0,Audio and video
8,268408,02-01-1970,M,4.0,1.264450e+10,14-08-2012,4.0,4.0,3.0,321.0,101.115,1064.115,TeleShop,Bags,4.0,Women
9,268408,02-01-1970,M,4.0,6.331455e+10,26-04-2012,1.0,1.0,1.0,806.0,84.630,890.630,Flagship store,Clothing,1.0,Women

In [15]:
cust_tran_prod.tail(10)

,customer_Id,DOB,Gender,city_code,transaction_id,tran_date,prod_subcat_code,prod_cat_code,Qty,Rate,Tax,total_amt,Store_type,prod_cat,prod_sub_cat_code,prod_subcat
23184,270476,25-12-1992,F,3.0,7.803441e+10,13-08-2013,11.0,6.0,1.0,971.0,101.955,1072.955,TeleShop,Home and kitchen,11.0,Bath
23185,270476,25-12-1992,F,3.0,3.359888e+09,16-03-2013,10.0,3.0,4.0,361.0,151.620,1595.620,MBR,Electronics,10.0,Audio and video
23186,270476,25-12-1992,F,3.0,2.288339e+10,22-05-2012,4.0,2.0,4.0,898.0,377.160,3969.160,Flagship store,Footwear,4.0,Kids
23187,270476,25-12-1992,F,3.0,1.972519e+10,21-02-2012,4.0,4.0,4.0,618.0,259.560,2731.560,e-Shop,Bags,4.0,Women
23188,270476,25-12-1992,F,3.0,8.547516e+10,9/8/2011,5.0,3.0,5.0,1354.0,710.850,7480.850,Flagship store,Electronics,5.0,Computers
23189,269626,27-12-1992,F,5.0,7.136903e+10,18-10-2011,12.0,6.0,1.0,638.0,66.990,704.990,e-Shop,Home and kitchen,12.0,Tools
23190,269626,27-12-1992,F,5.0,9.413405e+10,7/7/2011,3.0,1.0,3.0,1078.0,339.570,3573.570,MBR,Clothing,3.0,Kids
23191,274308,29-12-1992,F,5.0,2.620869e+10,22-10-2012,1.0,2.0,2.0,898.0,188.580,1984.580,MBR,Footwear,1.0,Mens
23192,274308,29-12-1992,F,5.0,5.735882e+10,5/9/2012,1.0,2.0,4.0,876.0,367.920,3871.920,e-Shop,Footwear,1.0,Mens
23193,274308,29-12-1992,F,5.0,5.816054e+10,4/7/2012,12.0,5.0,5.0,588.0,308.700,3248.700,e-Shop,Books,12.0,Academic

### c. “Five-number summary” for continuous variables (min, Q1, median, Q3 and max

In [16]:
five_number_summary=cust_tran_prod.loc[cust_tran_prod.Qty > 0,['Qty','Rate','total_amt','Tax']].describe().T
five_number_summary.loc[::,'min':'max']

             min         25%       50%      75%     max
Qty         1.00     2.00000     3.000     4.00     5.0
Rate       70.00   426.00000   788.000  1148.00  1500.0
total_amt  77.35  1030.68875  2089.555  3825.51  8287.5
Tax         7.35    97.93875   198.555   363.51   787.5

### d. Frequency tables for all the categorical variables

In [17]:
cat_cols = cust_tran_prod.select_dtypes('object').columns

for col in cat_cols:
    print(f"\nFrequency table for {col}")
    print(cust_tran_prod[col].value_counts())

Frequency table for DOB
DOB
17-09-1982    32
27-12-1988    32
25-02-1974    27
20-03-1972    25
18-11-1991    24
              ..
02-11-1988     1
05-11-1988     1
08-05-1981     1
04-05-1981     1
27-05-1981     1
Name: count, Length: 4056, dtype: int64

Frequency table for Gender
Gender
M    11877
F    11308
Name: count, dtype: int64

Frequency table for tran_date
tran_date
13-07-2011    35
23-10-2011    33
21-12-2013    33
25-09-2011    33
22-11-2011    33
              ..
24-02-2014     2
23-02-2014     2
27-02-2014     1
21-02-2014     1
28-02-2014     1
Name: count, Length: 1129, dtype: int64

Frequency table for Store_type
Store_type
e-Shop            9311
MBR               4661
Flagship store    4577
TeleShop          4504
Name: count, dtype: int64

Frequency table for prod_cat
prod_cat
Books               6069
Electronics         4898
Home and kitchen    4129
Footwear            2999
Clothing            2960
Bags                1998
Name: count, dtype: int64

Frequency table for prod_subcat
prod_subcat
Women                  3048
Mens                   2912
Kids                   1997
Tools                  1062
Fiction                1043
Kitchen                1037
Children               1035
Comics                 1031
Mobiles                1031
Bath                   1023
Furnishing             1007
Non-Fiction            1004
DIY                     989
Cameras                 985
Personal Appliances     972
Academic                967
Computers               958
Audio and video         952
Name: count, dtype: int64

In [18]:
cust_tran_prod['customer_Id']=cust_tran_prod['customer_Id'].astype('object')
cust_tran_prod['city_code']=cust_tran_prod['city_code'].astype('object')
cust_tran_prod['transaction_id']=cust_tran_prod['transaction_id'].astype('object')
cust_tran_prod['tran_date']=pd.to_datetime(cust_tran_prod['tran_date'],errors='coerce')
cust_tran_prod['DOB']=pd.to_datetime(cust_tran_prod['DOB'],format='%d-%m-%Y')
cust_tran_prod['prod_subcat_code']=cust_tran_prod['prod_subcat_code'].astype('object')
cust_tran_prod['prod_cat_code']=cust_tran_prod['prod_cat_code'].astype('object')
cust_tran_prod['prod_sub_cat_code']=cust_tran_prod['prod_sub_cat_code'].astype('object')

C:\Users\Asus\AppData\Local\Temp\ipykernel_20240\3125201354.py:4: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cust_tran_prod['tran_date']=pd.to_datetime(cust_tran_prod['tran_date'],errors='coerce')

### 3. Generate histograms for all continuous variables and frequency bars for categorical variables.

In [22]:
###def plot_data(df):
  ##  for col in df.columns:
   ##     if df[col].dtype in ['int64', 'float64']:   # continuous
        ###    df[col].plot(kind='hist', title=f'Histogram of {col}')
           
      ###  elif df[col].dtype == 'object' or str(df[col].dtype) == 'category':  # categorical
          ###  df[col].value_counts().plot(kind='bar', title=f'Bar plot of {col}')

In [19]:
##df=cust_tran_prod
##plot_data(df)

### 4. Calculate the following information using the merged dataset :
--------------------------------------------------------------------
#### a. Time period of the available transaction data

In [23]:
print('The starting date of the data set',cust_tran_prod.tran_date.max() )
print('The ending date of the data set',cust_tran_prod.tran_date.min() )

The starting date of the data set 2014-02-28 00:00:00
The ending date of the data set 2011-01-25 00:00:00

### b. Count of transactions where the total amount of transaction was negative

In [27]:
cust_tran_prod.loc[cust_tran_prod.Qty < 0].shape[0]

2177

### 5. Analyze which product categories are more popular among females vs male customers

In [42]:
popular_categories=cust_tran_prod.pivot_table(
    index='prod_cat',columns='Gender',values='transaction_id',aggfunc='count').reset_index().sort_values('F',ascending=False,ignore_index=True)
popular_categories.loc[::,'prod_cat'].head(1)

0    Books
Name: prod_cat, dtype: object

### 6. Which City code has the maximum customers and what was the percentage of customers from that city

In [74]:
max_cust=cust_tran_prod.groupby('city_code').customer_Id.nunique().reset_index()
p=max_cust.sort_values('customer_Id',ascending=False,ignore_index=True)
p['customer_percent']=(p.customer_Id/p.customer_Id.sum() )*100
p.rename({'customer_Id':'No_of_customer'},axis=1,inplace=True)
top_city=p.head(1)
top_city.iloc[0]

city_code             3.000000
No_of_customer      595.000000
customer_percent     10.540301
Name: 0, dtype: float64

 ### 7. Which store type sells the maximum products by value and by quantity

In [88]:
max_product=cust_tran_prod.loc[(cust_tran_prod.Qty >  0 ) & (cust_tran_prod.total_amt > 0) ]
store_max=max_product.groupby('Store_type')[['total_amt','Qty']].sum().round({'total_amt':2}).sort_values('total_amt',ascending=False)
store_max.head(1)

              total_amt      Qty
Store_type
e-Shop      22185609.88  25435.0

### 8. What was the total amount earned from the "Electronics" and "Clothing" categories from Flagship Stores

In [99]:
Total_amount=cust_tran_prod.loc[(cust_tran_prod.prod_cat.isin(['Electronics','Clothing']) ) &  (cust_tran_prod.Store_type == 'Flagship store') & (cust_tran_prod.Qty > 0) & (cust_tran_prod.total_amt > 0 )]
Total_amount.total_amt.sum()

np.float64(3851454.295)

### 9. What was the total amount earned from "Male" customers under the "Electronics" category?

In [104]:
total_revenu_by_male=cust_tran_prod.loc[
    (cust_tran_prod.Gender == 'M') & (cust_tran_prod.prod_cat == 'Electronics') & (cust_tran_prod.total_amt > 0) & (cust_tran_prod.Qty > 0)]
total_revenu_by_male.total_amt.sum()

np.float64(6315353.46)

### 10. How many customers have more than 10 unique transactions, after removing all transactions which have any negative amounts?

In [138]:
y=cust_tran_prod.loc[cust_tran_prod.total_amt > 0]
more_10=y.groupby('customer_Id').transaction_id.nunique().reset_index()
more_10.rename({'transaction_id':'No_of_nunique'},axis=1,inplace=True)
result=more_10.loc[more_10.No_of_nunique > 10].reset_index(drop=True)
result.shape[0]

6

In [150]:
today=pd.Timestamp.now()
cust_tran_prod['Age']=(today-cust_tran_prod.DOB).dt.days //365.25
cust_tran_prod.head(2)

,customer_Id,DOB,Gender,city_code,transaction_id,tran_date,prod_subcat_code,prod_cat_code,Qty,Rate,Tax,total_amt,Store_type,prod_cat,prod_sub_cat_code,prod_subcat,Age
0,268408,1970-01-02,M,4.0,87243835584.0,2014-01-13,7.0,5.0,5.0,187.0,98.175,1033.175,TeleShop,Books,7.0,Fiction,56.0
1,268408,1970-01-02,M,4.0,16197868036.0,2013-12-16,1.0,4.0,-5.0,-210.0,110.250,-1160.250,Flagship store,Bags,1.0,Mens,56.0

#### 11. For all customers aged between 25 - 35, find out:
------------------------------------------------------------
#### a. What was the total amount spent for “Electronics” and “Books” product categories?

In [159]:
spend=cust_tran_prod.loc[
    (cust_tran_prod.Age >=25) & (cust_tran_prod.Age <=35 ) & (cust_tran_prod.prod_cat.isin(['Electronics','Books'])) &(cust_tran_prod.total_amt > 0)]
spend.groupby('prod_cat').total_amt.sum().reset_index()

      prod_cat   total_amt
0        Books  1630951.27
1  Electronics  1243166.99

### b. What was the total amount spent by these customers between 1st Jan, 2014 to 1st Mar, 2014?

In [172]:
spent=cust_tran_prod.loc[
    (cust_tran_prod.Age >=25)&(cust_tran_prod.Age <=35) & (cust_tran_prod.tran_date >='2014-01-01') & (cust_tran_prod.tran_date <= '2014-03-01') &(cust_tran_prod.total_amt > 0)]
spent.total_amt.sum()

np.float64(166576.53999999998)

np.float64(155449.19)